### ISSUE TITLE
something weird about 'Tool' 

### ISSUE THREAD

**Issue by Jacoobr** [fidler-lab/polyrnn-pp-pytorch#14]
Hi, @amlankar. When I try to run Tool on my own server follow the part [tool](https://github.com/fidler-lab/polyrnn-pp-pytorch/blob/master/README.md#tool):
There are my command lines that running the backent and frontent separately:
1. backent
`python Tool/tool.py --exp /mnt/data/polygonRNN_pluss/code/Experiments/tool.json --reload /mnt/data/polygonRNN_pluss/models/ggnn_epoch5_step14000.pth --port 5001 --image_dir /mnt/data/polygonRNN_pluss/code/Tool/frontend/static/img/`
2. frontent
`python -m SimpleHTTPServer`
And then i get the index page as follow:
![e1](https://user-images.githubusercontent.com/25550204/51185176-628c2180-1911-11e9-875c-a58aae4f3471.PNG)

**the page above showed when i draw a box around an object like a car. The page just stoped when i draw a box around an object, and the progress bar just rolling endless.** 
the log at frontent terminal like this:

![e2](https://user-images.githubusercontent.com/25550204/51185199-6e77e380-1911-11e9-8584-c90d73879dfb.PNG)

the log at backent as follow:
```
Building dataloaders
Dataset Options:  {u'img_side': 224, u'random_context': [0.15, 0.15], u'flip': False, u'batch_size': 1, u'random_start': False, u'grid_side': 28, u'max_poly_len': 71}
Building polyrnnpp with opts:
{u'ggnn_n_steps': 5, u'temperature': 0.0, u'ggnn_grid_size': 112, u'ggnn_output_dim': 15, u'use_bn_lstm': True, u'ggnn_state_dim': 1024, u'return_attention': False, u'mode': u'tool', u'use_evaluator': True, u'dataset': {u'train_val': {u'img_side': 224, u'random_context': [0.15, 0.15], u'flip': False, u'batch_size': 1, u'random_start': False, u'grid_side': 28, u'max_poly_len': 71}}, u'use_ggnn': True, u'use_separate_encoder': False, u'max_poly_len': 71}
Building encoder
Building first vertex network
Building convlstm
Building Evaluator
Building GGNN
Building GGNN Feature Encoder
Reloading full model from:  /mnt/data/polygonRNN_pluss/models/ggnn_epoch5_step14000.pth
 * Serving Flask app "tool" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Running on http://0.0.0.0:5001/ (Press CTRL+C to quit)
 * Restarting with stat
Building dataloaders
Dataset Options:  {u'img_side': 224, u'random_context': [0.15, 0.15], u'flip': False, u'batch_size': 1, u'random_start': False, u'grid_side': 28, u'max_poly_len': 71}
Building polyrnnpp with opts:
{u'ggnn_n_steps': 5, u'temperature': 0.0, u'ggnn_grid_size': 112, u'ggnn_output_dim': 15, u'use_bn_lstm': True, u'ggnn_state_dim': 1024, u'return_attention': False, u'mode': u'tool', u'use_evaluator': True, u'dataset': {u'train_val': {u'img_side': 224, u'random_context': [0.15, 0.15], u'flip': False, u'batch_size': 1, u'random_start': False, u'grid_side': 28, u'max_poly_len': 71}}, u'use_ggnn': True, u'use_separate_encoder': False, u'max_poly_len': 71}
Building encoder
Building first vertex network
Building convlstm
Building Evaluator
Building GGNN
Building GGNN Feature Encoder
Reloading full model from:  /mnt/data/polygonRNN_pluss/models/ggnn_epoch5_step14000.pth
 * Debugger is active!
 * Debugger PIN: 294-205-619
```
I can't get the annotation file of the tool and see the polygon on the page when i draw a bbox around an object.Can you give me some advice about this? Much appreciated for your reply.

What's more , when i try to see the backend with chrome browser by localhost:5001, i get 404 respond like bellow:
`127.0.0.1 -- "GET / HTTP/1.1" 404 -`
Does that means the backent not work?

**Comment by amlankar** [comment]
Hi @Jacoobr, I tried but failed to reproduce this bug. 

The only difference I see is that your flask app (backend) is running in development mode with the debugger turned on. Can you try running it in production mode with the debugger turned off?

**Comment by Jacoobr** [comment]
Hi, @amlankar ,thanks for your reply. i changed the environment  mode to production and turned off the debuger mode.  but the issue still as the same. Can you tell me what browser you used on your service?, bth, i used google chrome browser with Ubuntu16.04 environment.

**Comment by amlankar** [comment]
I'm sorry, I still cannot reproduce this issue on my own machine. I followed the exact instructions from the README. Here is a screenshot from running the code from a fresh download. 

**NOTES**
* Since I ran this on my (very small) CPU, it took around 20 seconds to run, as you can see from the log on the backend server process. (top of the two bottom right terminals on the screen)
* The globalFolder variable in the js has to be an absolute path (bottom left terminal on the screen)

![demo_running](https://user-images.githubusercontent.com/7633212/52972577-502a5b00-3389-11e9-8cac-6f100a4d3e2a.png)

**UPLOADING AN IMAGE**
Uploading images also works fine for me, here is a screenshot of me uploading the screenshot I posted above on the tool. You can see there's a upload request on the backend logs.

![demo_upload](https://user-images.githubusercontent.com/7633212/52972866-30476700-338a-11e9-9251-17ef442f65b0.png)

**Comment by Jacoobr** [comment]
Hi, @amlankar. Thanks for your patience working throught on my issue. I fixed my problem by runing bakend and frontent separately on different two hosts. My issue of previous may caused by runing bakend and frontent on my distant server and using ssh tools like 'MobaXterm' in my lab host to communicate. So, the frontent didn't work when i called ip:8000 on my lab host.

**Comment by wenmengliu** [comment]
@Jacoobr. I have the exact issue as you. I also tried to run the backend at my server and test the frontend at my own computer. But it still doesn't work.  Could you please offer me more hints? Thx

**Comment by troylhy1991** [comment]
Hi, @Jacoobr . Same problem here. The loader logo keeps blinking. How do u fix the problem separating backend and frontend on different hosts. I'm using mobaxterm and ssh to the lab server. Thanks!

**Comment by Flames60** [comment]
> Hi, @amlankar. Thanks for your patience working throught on my issue. I fixed my problem by runing bakend and frontent separately on different two hosts. My issue of previous may caused by runing bakend and frontent on my distant server and using ssh tools like 'MobaXterm' in my lab host to communicate. So, the frontent didn't work when i called ip:8000 on my lab host.

Do you mean you put the frontend and backend on 2 lab hosts seperately, and you use MobaXterm to ssh them?

**Comment by Flames60** [comment]
> I'm sorry, I still cannot reproduce this issue on my own machine. I followed the exact instructions from the README. Here is a screenshot from running the code from a fresh download.
> 
> **NOTES**
> 
> * Since I ran this on my (very small) CPU, it took around 20 seconds to run, as you can see from the log on the backend server process. (top of the two bottom right terminals on the screen)
> * The globalFolder variable in the js has to be an absolute path (bottom left terminal on the screen)
> 
> ![demo_running](https://user-images.githubusercontent.com/7633212/52972577-502a5b00-3389-11e9-8cac-6f100a4d3e2a.png)
> 
> **UPLOADING AN IMAGE**
> Uploading images also works fine for me, here is a screenshot of me uploading the screenshot I posted above on the tool. You can see there's a upload request on the backend logs.
> 
> ![demo_upload](https://user-images.githubusercontent.com/7633212/52972866-30476700-338a-11e9-9251-17ef442f65b0.png)

How to use CPU only?

> I'm sorry, I still cannot reproduce this issue on my own machine. I followed the exact instructions from the README. Here is a screenshot from running the code from a fresh download.
> 
> **NOTES**
> 
> * Since I ran this on my (very small) CPU, it took around 20 seconds to run, as you can see from the log on the backend server process. (top of the two bottom right terminals on the screen)
> * The globalFolder variable in the js has to be an absolute path (bottom left terminal on the screen)
> 
> ![demo_running](https://user-images.githubusercontent.com/7633212/52972577-502a5b00-3389-11e9-8cac-6f100a4d3e2a.png)
> 
> **UPLOADING AN IMAGE**
> Uploading images also works fine for me, here is a screenshot of me uploading the screenshot I posted above on the tool. You can see there's a upload request on the backend logs.
> 
> ![demo_upload](https://user-images.githubusercontent.com/7633212/52972866-30476700-338a-11e9-9251-17ef442f65b0.png)

Hi, @amlankar. How to use CPU only?

**Comment by Flames60** [comment]
> Hi, @Jacoobr . Same problem here. The loader logo keeps blinking. How do u fix the problem separating backend and frontend on different hosts. I'm using mobaxterm and ssh to the lab server. Thanks!

Hi, have you fixed the problem? I am facing the same problem.

**Comment by Flames60** [comment]
> Hi, @Jacoobr . Same problem here. The loader logo keeps blinking. How do u fix the problem separating backend and frontend on different hosts. I'm using mobaxterm and ssh to the lab server. Thanks!

I have fix it. You just need to edit the value of 'backend' in 'index.html', for example, use the IP address rather than 'localhost'.
